name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '2.1']

    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build and Analyze code
        run: |
          dotnet restore
          dotnet build --no-restore
          dotnet tool install -g roslynator.dotnet.cli
          dotnet roslynator analyze -f msvs -o report.xml

      - name: Upload Code Analysis Report
        uses: actions/upload-artifact@v2
        with:
          name: Code Analysis Report
          path: report.xml


