name: dotnet diagnostic

on: [push]

jobs:
  build-csharp-solution:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: ['2.1']

    steps:
    - uses: actions/checkout@v3

    - name: Build project
      run: dotnet build
