name: dotnet store

on: [push]

jobs:
  build-test:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: ['2.1']

    steps:
    - uses: actions/checkout@v3

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --verbosity diagnostic > build.log 2>&1 || true
      
    - name: Upload build log
      uses: actions/upload-artifact@v2
      with:
        name: build-log
        path: build.log

