name: Build and test code

on: [push]

jobs:
  build-csharp-solution:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: ['2.1']

    steps:
    - uses: actions/checkout@v3

    - name: Build project
      run: dotnet build
      
    - name: Run test in project
      run: dotnet test --logger "trx;LogFileName=test-results.trx" || true

    - name: Report test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"                           
        reporter: dotnet-trx
