name: dotnet diagnostic

on: [push]

jobs:
  build-csharp-solution:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: ['2.1']

    steps:
    - uses: actions/checkout@v3

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build solution and collect results
      run: dotnet build --configuration Release --verbosity minimal > build.log
      
    - name: Przeczytaj plik z wynikiem i zapisz do zmiennej
      id: build_results
      run: echo "::set-output name=build_results::$(cat build.log
      
    - name: Diagnostic Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        format: "dotnet"
        build: "${{ github.sha }}"
        coverage: "${{ steps.coverage_report.outputs.coverage }}"
        test_results: "${{ steps.build_results.outputs.build_results }}"

