name: dotnet diagnostic

on: [push]

jobs:
  build-csharp-solution:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: ['2.1']

    steps:
    - uses: actions/checkout@v3

    - name: Build project
      run: dotnet build --configuration Release

    - name: Analyze code
      uses: github/codeql-action/analyze@v1
      with:
        languages: csharp
        query: security/ql/src/CodeQL-Queries/CSharp/Security/CWE-119/CWE-119.ql


