name: Check .mat file names

on: [push, pull_request]

jobs:
  check-mat-file-names:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: ['2.1']
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Build project
      run: dotnet build
        
    - name: Check .mat file names
      run: |
        shopt -s globstar
        for file in find . -name '*.cs'; do
          echo "File name '$file' "
        done
