name: Check .mat file names

on: [push, pull_request]

jobs:
  check-mat-file-names:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: ['2.1']
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Build project
      run: dotnet build
        
    - name: Check .mat file names
      run: |
        csfiles=$(find . -name '*.cs' -print)
        for file in $csfiles; do
          filename=$(basename $file)
          if [[ ${filename:0:1} =~ [[:upper:]] ]]; then
            echo "$filename starts with an uppercase letter"
          else
            echo "$filename does not start with an uppercase letter"
          fi
        done

