name: Check .mat file names

on: [pull_request]

jobs:
  check-mat-file-names:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: ['2.1']
        
    steps:
    - uses: actions/checkout@v3
           
    - name: Check .mat file names
      run: |
        matfiles=$(find . -name '*.mat' -print)
        not_valid_files=()
        
        for file in $matfiles 
        do
          filename=$(basename $file)
          if [[ ${filename:0:1} != [[:upper:]] ]]; then
            not_valid_files+=($filename)
          fi
        done
        
        if [ ${#not_valid_files[@]} -gt 0 ]; then
          for (( i=0; i<${#not_valid_files[@]}; i++ ))
          do
            echo "${not_valid_files[$i]} is not nammed with uppercase!"
          done
          exit 1
        fi




